---
all:
  hosts:
    nexus-01:
      ansible_host: 130.193.44.27
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection: ssh
    ansible_user: yachi
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
